FROM open-liberty:21.0.0.9-kernel-slim-java8-openj9

RUN featureUtility installFeature jsp-2.3
RUN featureUtility installFeature localConnector-1.0
RUN featureUtility installFeature servlet-4.0
RUN featureUtility installFeature ejbLite-3.2
RUN featureUtility installFeature ejbHome-3.2
RUN featureUtility installFeature ejbRemote-3.2
